import React, { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import {
  FaAws,
  FaBell,
  FaChartLine,
  FaCog,
  FaDropbox,
  FaFolder,
  FaGoogleDrive,
  FaInstagram,
  FaKey,
  FaQuestionCircle,
  FaSignOutAlt,
  FaSlack,
  FaTimes,
  FaVimeoV,
  FaYoutube,
  FaCheck,
  FaPlug,
  FaVideo
} from 'react-icons/fa'
import { motion, AnimatePresence } from 'framer-motion'
import { useAuth } from '../context/AuthContext'
import { PremiumDevicePreview, SignalPill } from './PremiumVisuals'
import '../index.css'

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'

const PROVIDERS_META = {
  youtube: {
    name: 'YouTube',
    icon: <FaYoutube />,
    color: '#ef4444',
    bg: 'from-red-500 to-red-600',
    helper: 'Connect using OAuth client details for auto-publishing Shorts.',
    about: 'Automate your organic growth engine. Connect your Locaa AI workspace directly to your YouTube channel to publish full videos and Shorts effortlessly without leaving the dashboard.',
    features: ['Direct high-res publishing', 'Auto-schedule YouTube Shorts', 'SEO AI metadata generation'],
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Google OAuth Client ID' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Google OAuth Client Secret', secret: true },
      { key: 'api_key', label: 'API Key (optional)', placeholder: 'YouTube Data API key', secret: true },
      { key: 'redirect_uri', label: 'Redirect URI (optional)', placeholder: 'http://localhost:5000/oauth/callback' },
    ],
  },
  instagram: {
    name: 'Instagram',
    icon: <FaInstagram />,
    color: '#ec4899',
    bg: 'from-pink-500 to-purple-500',
    helper: 'Use Instagram Graph app credentials to publish Reels.',
    about: 'Tap into Instagram\'s massive audience. Automatically syndicate your AI-generated clips to Reels and Grid to keep your followers engaged with consistent, high-quality content.',
    features: ['Auto-publish Reels', 'Custom cover frame selection', 'Cross-post to Feed'],
    fields: [
      { key: 'app_id', label: 'App ID', placeholder: 'Instagram App ID' },
      { key: 'app_secret', label: 'App Secret', placeholder: 'Instagram App Secret', secret: true },
      { key: 'access_token', label: 'Access Token', placeholder: 'Long-lived access token', secret: true },
    ],
  },
  tiktok: {
    name: 'TikTok',
    icon: <span className="font-bold text-xl leading-none">T</span>,
    color: '#06b6d4',
    bg: 'from-cyan-400 to-blue-500',
    helper: 'Use TikTok developer app credentials.',
    about: 'Go viral faster. Connect your TikTok Business account to instantly post trending clips generated by our AI directly to your feed.',
    features: ['Direct TikTok Webhook publishing', 'Trend-aware tags', 'Analytics sync'],
    fields: [
      { key: 'client_key', label: 'Client Key', placeholder: 'TikTok Client Key' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'TikTok Client Secret', secret: true },
      { key: 'access_token', label: 'Access Token', placeholder: 'TikTok Access Token', secret: true },
    ],
  },
  google_drive: {
    name: 'Google Drive',
    icon: <FaGoogleDrive />,
    color: '#3b82f6',
    bg: 'from-blue-400 to-blue-600',
    helper: 'Sync generated videos to Google Drive automatically.',
    about: 'Never lose a clip. Connect your Google Workspace to automatically backup all generated assets, making it easy to share raw files with your editing team.',
    features: ['Automatic cloud backup', 'Team folder sharing', 'Organized generated assets'],
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Google Client ID' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Google Client Secret', secret: true },
    ],
  },
  dropbox: {
    name: 'Dropbox',
    icon: <FaDropbox />,
    color: '#2563eb',
    bg: 'from-blue-500 to-blue-700',
    helper: 'Back up your clips to a Dropbox folder.',
    about: 'Enterprise grade storage for your startup. Sync your entire catalog of dubbed and chopped clips straight to your secure Dropbox environment.',
    features: ['Secure asset storage', 'Version history support', 'Seamless agency handoff'],
    fields: [
      { key: 'access_token', label: 'Access Token', placeholder: 'Dropbox Access Token', secret: true },
    ],
  },
  vimeo: {
    name: 'Vimeo',
    icon: <FaVimeoV />,
    color: '#0ea5e9',
    bg: 'from-sky-400 to-sky-600',
    helper: 'Configure Vimeo API key for high-quality portfolio hosting.',
    about: 'Present your brand professionally. Push your high-quality corporate and startup pitch videos directly to Vimeo for ad-free hosting and custom embeds.',
    features: ['Ad-free video hosting', 'Custom player embeds', 'High bitrate 4k support'],
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Vimeo API Key', secret: true },
    ],
  },
  slack: {
    name: 'Slack',
    icon: <FaSlack />,
    color: '#8b5cf6',
    bg: 'from-violet-500 to-purple-600',
    helper: 'Get notifications when processing finishes or fails.',
    about: 'Keep your team in the loop. Receive instant Slack notifications when large batch processing jobs finish or when AI dubbing hits a roadblock.',
    features: ['Real-time job alerts', 'Error tracing', 'Team productivity boost'],
    fields: [
      { key: 'bot_token', label: 'Bot Token', placeholder: 'xoxb-...', secret: true },
    ],
  },
  aws_s3: {
    name: 'AWS S3',
    icon: <FaAws />,
    color: '#f97316',
    bg: 'from-orange-400 to-orange-600',
    helper: 'Store media outputs in an S3 bucket for enterprise compliance.',
    about: 'Scale infinitely. Hook your AWS environment to our pipeline to dump hundreds of gigabytes of generated social media clips straight into your private S3 buckets.',
    features: ['Infinite scale storage', 'Enterprise compliance', 'Custom IAM roles'],
    fields: [
      { key: 'access_key_id', label: 'Access Key ID', placeholder: 'AWS Access Key ID' },
      { key: 'secret_access_key', label: 'Secret Access Key', placeholder: 'AWS Secret Access Key', secret: true },
      { key: 'bucket_name', label: 'Bucket Name', placeholder: 'my-bucket' },
      { key: 'region', label: 'Region', placeholder: 'ap-south-1' },
    ],
  },
}

function Integrations() {
  const navigate = useNavigate()
  const { user, logout, token } = useAuth()
  const [integrations, setIntegrations] = useState({})
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [modalProvider, setModalProvider] = useState(null)
  const [activeTab, setActiveTab] = useState('overview')
  const [formValues, setFormValues] = useState({})
  const [notice, setNotice] = useState(null)

  const handleLogout = () => {
    logout()
    navigate('/login')
  }

  const sidePrimaryItems = [
    { label: 'Dashboard', icon: '▦', path: '/dashboard' },
    { label: 'My Projects', icon: '◫', path: '/settings' },
    // { label: 'Clip Maker', icon: '✂', path: '/create' },
    // { label: 'Logo & Branding', icon: '✎', path: '/branding' },
    // { label: 'Upload Manager', icon: '⤴', path: '/dashboard' },
    { label: 'Team Collab', icon: '⎈', path: '/team-collaboration' },
    { label: 'Integrations', icon: '◌', path: '/integrations', active: true },
  ]

  const sideSecondaryItems = [
    { label: 'Analytics', icon: <FaChartLine />, path: '/analytics' },
    { label: 'Pricing & Plan', icon: <FaFolder />, path: '/pricing' },
    { label: 'Profile Settings', icon: <FaCog />, path: '/profile' },
    { label: 'Support & Docs', icon: <FaQuestionCircle />, path: '/support-docs' },
    // { label: 'API Access', icon: <FaKey />, meta: 'For devs', path: '/profile?tab=security' },
  ]

  const fetchIntegrations = async () => {
    try {
      setLoading(true)
      const accessToken = token || localStorage.getItem('access_token')
      const response = await axios.get(`${API_BASE}/api/integrations`, {
        headers: { Authorization: `Bearer ${accessToken}` },
      })

      const mapped = {}
      response.data.forEach((item) => {
        mapped[item.provider] = item
      })
      setIntegrations(mapped)
    } catch (error) {
      // Silent error for UX, or handle appropriately
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchIntegrations()
  }, [])

  const openProviderModal = (provider) => {
    const existing = integrations[provider]?.config_editable || {}
    setModalProvider(provider)
    setFormValues(existing)
    setActiveTab('overview')
    setNotice(null)
  }

  const closeProviderModal = () => {
    setModalProvider(null)
    setFormValues({})
  }

  const handleSaveProvider = async () => {
    if (!modalProvider) return

    try {
      setSaving(true)
      const accessToken = token || localStorage.getItem('access_token')
      await axios.put(
        `${API_BASE}/api/integrations/${modalProvider}`,
        { config: formValues },
        { headers: { Authorization: `Bearer ${accessToken}` } }
      )

      setNotice({ type: 'success', text: 'Settings saved successfully.' })
      await fetchIntegrations()
      closeProviderModal()

      // Clear notice after 3 seconds
      setTimeout(() => setNotice(null), 3000)
    } catch (error) {
      setNotice({ type: 'error', text: error?.response?.data?.error || 'Failed to save integration.' })
    } finally {
      setSaving(false)
    }
  }

  const handleDisconnect = async (provider) => {
    if (!window.confirm(`Are you sure you want to disconnect ${PROVIDERS_META[provider].name}?`)) return

    try {
      const accessToken = token || localStorage.getItem('access_token')
      await axios.post(
        `${API_BASE}/api/integrations/${provider}/disconnect`,
        {},
        { headers: { Authorization: `Bearer ${accessToken}` } }
      )
      setNotice({ type: 'success', text: `${PROVIDERS_META[provider].name} disconnected.` })
      await fetchIntegrations()
      setTimeout(() => setNotice(null), 3000)
    } catch (error) {
      setNotice({ type: 'error', text: error?.response?.data?.error || 'Disconnect failed.' })
    }
  }

  const cardProviders = useMemo(
    () => ['youtube', 'instagram', 'tiktok', 'google_drive', 'dropbox', 'vimeo', 'slack', 'aws_s3'],
    []
  )

  const modalMeta = modalProvider ? PROVIDERS_META[modalProvider] : null
  const integrationStats = [
    { value: `${cardProviders.length}`, label: 'available apps' },
    { value: `${Object.values(integrations).filter((item) => item?.is_connected).length}`, label: 'live connections' },
    { value: '24/7', label: 'sync monitoring' },
  ]

  return (
    <div className="flex h-screen bg-dark-900 text-dark-50 font-sans overflow-hidden relative">
      {/* Ambient Background Elements */}
      <div className="absolute top-[-10%] left-[-10%] w-[40vw] h-[40vw] bg-primary-500/10 rounded-full mix-blend-screen filter blur-[100px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40vw] h-[40vw] bg-blue-500/10 rounded-full mix-blend-screen filter blur-[100px] pointer-events-none" />

      {/* Sidebar */}
      <aside className="w-64 bg-dark-900/50 backdrop-blur-xl border-r border-white/5 flex flex-col z-10 hidden md:flex">
        <div className="p-6 flex items-center gap-3 border-b border-white/5">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary-500 to-blue-500 flex items-center justify-center font-display font-bold text-white text-lg shadow-lg shadow-primary-500/30">
            L
          </div>
          <span className="font-display font-bold text-xl text-white tracking-tight">Locaa AI</span>
        </div>

        <div className="flex-1 overflow-y-auto px-4 py-6 space-y-8 custom-scrollbar">
          <nav className="space-y-1">
            <p className="px-3 text-xs font-semibold text-dark-400 uppercase tracking-wider mb-2">Main Menu</p>
            {sidePrimaryItems.map((item) => (
              <a
                href="#"
                key={item.label}
                onClick={(e) => { e.preventDefault(); navigate(item.path); }}
                className={`flex items-center justify-between px-3 py-2.5 rounded-xl transition-all duration-200 group ${item.active
                  ? 'bg-primary-500/10 text-primary-400 font-medium'
                  : 'text-dark-300 hover:bg-white/5 hover:text-white'
                  }`}
              >
                <div className="flex items-center gap-3">
                  <span className={`text-lg ${item.active ? 'text-primary-400' : 'text-dark-400 group-hover:text-white'}`}>
                    {item.icon}
                  </span>
                  <span>{item.label}</span>
                </div>
                {item.active && <div className="w-1.5 h-1.5 rounded-full bg-primary-500 shadow-[0_0_8px_rgba(20,184,166,0.8)]"></div>}
              </a>
            ))}
          </nav>

          <nav className="space-y-1">
            <p className="px-3 text-xs font-semibold text-dark-400 uppercase tracking-wider mb-2">Preferences</p>
            {sideSecondaryItems.map((item) => (
              <a
                href="#"
                key={item.label}
                onClick={(e) => { e.preventDefault(); navigate(item.path); }}
                className="flex items-center justify-between px-3 py-2.5 rounded-xl text-dark-300 hover:bg-white/5 hover:text-white transition-all duration-200 group"
              >
                <div className="flex items-center gap-3">
                  <span className="text-lg text-dark-400 group-hover:text-white transition-colors">
                    {item.icon}
                  </span>
                  <span>{item.label}</span>
                </div>
                {item.meta && (
                  <span className="text-[10px] uppercase tracking-wider bg-dark-800 text-dark-300 px-2 py-0.5 rounded-full border border-white/5">
                    {item.meta}
                  </span>
                )}
              </a>
            ))}
          </nav>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col z-10 relative h-full overflow-hidden">
        {/* Top Header */}
        <header className="h-20 bg-dark-900/50 backdrop-blur-md border-b border-white/5 flex items-center justify-between px-8 sticky top-0 z-20">
          <h1 className="text-2xl font-display font-bold text-white flex items-center gap-3">
            <span className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center text-primary-400 text-sm border border-white/10">
              <FaPlug />
            </span>
            Integrations
          </h1>

          <div className="flex items-center gap-6">
            <button className="relative text-dark-300 hover:text-white transition-colors">
              <FaBell className="text-xl" />
            </button>
            <div className="h-8 w-px bg-white/10"></div>
            <div className="flex items-center gap-3">
              <div className="text-right hidden sm:block">
                <p className="text-sm font-semibold text-white leading-none mb-1">
                  {user?.name || user?.email?.split('@')[0] || 'User'}
                </p>
                <p className="text-xs text-primary-400 font-medium leading-none">Pro Plan</p>
              </div>
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-600 to-blue-600 flex items-center justify-center text-white font-bold shadow-lg shadow-primary-500/20 ring-2 ring-white/10">
                {user?.name?.[0] || 'A'}
              </div>
              <button
                className="ml-2 text-dark-400 hover:text-red-400 transition-colors p-2 rounded-lg hover:bg-white/5"
                onClick={handleLogout}
                title="Sign out"
              >
                <FaSignOutAlt />
              </button>
            </div>
          </div>
        </header>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">

          <div className="max-w-6xl mx-auto">
            <div className="mb-10 grid grid-cols-1 xl:grid-cols-[1.05fr_0.95fr] gap-6 items-center">
              <div className="rounded-[2rem] border border-white/10 bg-dark-800/30 p-8 backdrop-blur-xl overflow-hidden relative">
                <div className="absolute top-0 right-0 w-56 h-56 bg-primary-500/10 blur-[80px] rounded-full" />
                <div className="relative z-10">
                  <div className="flex flex-wrap gap-2 mb-4">
                    <SignalPill tone="primary">Distribution Layer</SignalPill>
                    <SignalPill tone="blue">Auto publish</SignalPill>
                    <SignalPill>Cloud backup</SignalPill>
                  </div>
                  <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-3">Connect your ecosystem like a premium content stack</h2>
                  <p className="text-dark-400 max-w-2xl leading-relaxed">Connect your social media and cloud storage accounts to automatically publish generated clips and back up your full videos without leaving the dashboard.</p>
                  <div className="grid grid-cols-3 gap-3 mt-6 max-w-xl">
                    {integrationStats.map((stat) => (
                      <div key={stat.label} className="rounded-2xl border border-white/10 bg-dark-900/40 p-3">
                        <p className="text-2xl font-display font-bold text-white">{stat.value}</p>
                        <p className="text-[10px] uppercase tracking-[0.18em] text-dark-500">{stat.label}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              <PremiumDevicePreview
                title="Integration Hub"
                subtitle="Publishing and storage orchestration"
                accent="violet"
                items={[
                  { label: 'YouTube sync', value: integrations.youtube?.is_connected ? 'Connected' : 'Pending', progress: integrations.youtube?.is_connected ? '88%' : '28%' },
                  { label: 'Instagram relay', value: integrations.instagram?.is_connected ? 'Connected' : 'Pending', progress: integrations.instagram?.is_connected ? '82%' : '18%' },
                  { label: 'Cloud backup', value: integrations.google_drive?.is_connected || integrations.dropbox?.is_connected ? 'Active' : 'Optional', progress: integrations.google_drive?.is_connected || integrations.dropbox?.is_connected ? '74%' : '22%' },
                ]}
              />
            </div>

            <AnimatePresence>
              {notice && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className={`mb-8 p-4 rounded-xl flex items-center gap-3 text-sm font-medium ${notice.type === 'error'
                    ? 'bg-red-500/10 border border-red-500/20 text-red-400'
                    : 'bg-green-500/10 border border-green-500/20 text-green-400'
                    }`}
                >
                  {notice.type === 'error' ? '⚠️' : '✅'} {notice.text}
                </motion.div>
              )}
            </AnimatePresence>

            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
              {cardProviders.map((provider) => {
                const meta = PROVIDERS_META[provider]
                const state = integrations[provider]
                const connected = Boolean(state?.is_connected)

                return (
                  <div key={provider} className="glass-panel p-6 bg-dark-800/40 hover:bg-dark-800/60 transition-all border-white/5 flex flex-col group h-full">
                    <div className="flex items-start justify-between mb-4">
                      <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${meta.bg} flex items-center justify-center text-2xl text-white shadow-lg`}>
                        {meta.icon}
                      </div>
                      <div className="flex flex-col items-end">
                        <span className={`px-2.5 py-1 text-[10px] uppercase tracking-wider font-bold rounded-full border backdrop-blur-md ${connected
                          ? 'bg-green-500/20 text-green-300 border-green-500/30'
                          : 'bg-dark-700/50 text-dark-400 border-white/10'
                          }`}>
                          {connected ? 'Connected' : 'Not Connected'}
                        </span>
                      </div>
                    </div>

                    <h3 className="text-lg font-bold text-white mb-2">{meta.name}</h3>
                    <p className="text-sm text-dark-400 mb-6 flex-1 line-clamp-2">{meta.helper}</p>

                    <div className="flex gap-3 mt-auto pt-4 border-t border-white/5">
                      {connected ? (
                        <>
                          <button
                            className="flex-1 btn-primary py-2 text-sm rounded-lg"
                            onClick={() => openProviderModal(provider)}
                          >
                            Manage
                          </button>
                          <button
                            className="bg-red-500/10 text-red-400 hover:bg-red-500/20 py-2 px-4 rounded-lg text-sm font-semibold transition-colors border border-red-500/20"
                            onClick={() => handleDisconnect(provider)}
                          >
                            Disconnect
                          </button>
                        </>
                      ) : (
                        <button
                          className="w-full bg-dark-700 hover:bg-white/10 text-white py-2 rounded-lg text-sm font-semibold transition-colors border border-white/10 flex items-center justify-center gap-2"
                          onClick={() => openProviderModal(provider)}
                        >
                          Connect
                        </button>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        </div>

        {/* Modal Overlay */}
        <AnimatePresence>
          {modalProvider && modalMeta && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-dark-900/80 backdrop-blur-sm"
            >
              <motion.div
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.95, opacity: 0 }}
                className="glass-panel w-full max-w-2xl bg-dark-800/90 border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
              >
                <div className="p-6 border-b border-white/5 flex items-center justify-between shrink-0">
                  <div className="flex items-center gap-4">
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${modalMeta.bg} flex items-center justify-center text-2xl text-white shadow-lg`}>
                      {modalMeta.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-display font-bold text-white leading-tight">{modalMeta.name} Integration</h3>
                      <p className="text-sm text-dark-400">Manage connection settings</p>
                    </div>
                  </div>
                  <button onClick={closeProviderModal} className="text-dark-400 hover:text-white transition-colors p-2 rounded-lg hover:bg-white/5">
                    <FaTimes />
                  </button>
                </div>

                {/* Tabs Context */}
                <div className="flex px-6 border-b border-white/5 shrink-0">
                  <button
                    className={`pb-3 pt-4 px-4 text-sm font-semibold transition-colors border-b-2 ${activeTab === 'overview' ? 'text-primary-400 border-primary-500' : 'text-dark-400 border-transparent hover:text-white'}`}
                    onClick={() => setActiveTab('overview')}
                  >
                    Overview
                  </button>
                  <button
                    className={`pb-3 pt-4 px-4 text-sm font-semibold transition-colors border-b-2 ${activeTab === 'settings' ? 'text-primary-400 border-primary-500' : 'text-dark-400 border-transparent hover:text-white'}`}
                    onClick={() => setActiveTab('settings')}
                  >
                    Configuration
                  </button>
                </div>

                <div className="p-6 overflow-y-auto custom-scrollbar flex-1">

                  {activeTab === 'overview' && (
                    <motion.div
                      key="overview"
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      className="space-y-6"
                    >
                      <div>
                        <h4 className="text-lg font-bold text-white mb-2">About {modalMeta.name} Integration</h4>
                        <p className="text-dark-300 leading-relaxed text-sm">
                          {modalMeta.about || modalMeta.helper}
                        </p>
                      </div>

                      {modalMeta.features && modalMeta.features.length > 0 && (
                        <div>
                          <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-3">Key Capabilities</h4>
                          <ul className="space-y-3">
                            {modalMeta.features.map((feat, idx) => (
                              <li key={idx} className="flex items-start gap-3">
                                <div className="w-5 h-5 rounded-full bg-primary-500/20 text-primary-400 flex items-center justify-center shrink-0 mt-0.5">
                                  <FaCheck className="text-[10px]" />
                                </div>
                                <span className="text-sm text-dark-300">{feat}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}

                      <div className="bg-primary-500/10 border border-primary-500/20 rounded-xl p-4 flex items-start gap-3 mt-4">
                        <FaQuestionCircle className="text-primary-400 text-lg shrink-0 mt-0.5" />
                        <div>
                          <p className="text-sm text-primary-200 font-medium">Need help finding your credentials?</p>
                          <p className="text-xs text-primary-400/70 mt-1">
                            Visit the developer console for {modalMeta.name} to generate your API keys, or read our step-by-step setup documentation.
                          </p>
                        </div>
                      </div>
                    </motion.div>
                  )}

                  {activeTab === 'settings' && (
                    <motion.div
                      key="settings"
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                    >
                      <p className="text-sm text-dark-300 mb-6">{modalMeta.helper}</p>

                      <div className="space-y-5">
                        {modalMeta.fields.map((field) => {
                          const savedHash = integrations[modalProvider]?.config_masked?.[field.key]
                          return (
                            <div key={field.key} className="space-y-2">
                              <label className="text-sm font-medium text-dark-300 block">{field.label}</label>
                              <input
                                type={field.secret ? 'password' : 'text'}
                                value={formValues[field.key] || ''}
                                onChange={(e) => setFormValues((prev) => ({ ...prev, [field.key]: e.target.value }))}
                                placeholder={field.placeholder}
                                className="w-full bg-dark-900 border border-white/10 focus:border-primary-500 focus:ring-1 focus:ring-primary-500 rounded-xl px-4 py-3 text-white placeholder-dark-600 transition-all font-mono text-sm shadow-inner"
                              />
                              {savedHash && !formValues[field.key] && (
                                <p className="text-xs text-green-400 flex items-center gap-1.5 mt-2 bg-green-500/10 w-fit px-2 py-1 rounded-md border border-green-500/20">
                                  <FaCheck /> Saved value: {savedHash} (leave blank to keep)
                                </p>
                              )}
                            </div>
                          )
                        })}
                      </div>
                    </motion.div>
                  )}
                </div>

                <div className="p-6 border-t border-white/5 bg-dark-900/80 flex justify-between items-center shrink-0">
                  <div className="text-xs text-dark-500 font-medium px-2">
                    {activeTab === 'settings' ? 'API keys are stored securely using encryption.' : ''}
                  </div>
                  <div className="flex gap-3">
                    <button
                      onClick={closeProviderModal}
                      className="px-5 py-2.5 bg-dark-700 hover:bg-dark-600 text-white rounded-xl text-sm font-semibold transition-colors"
                    >
                      {activeTab === 'overview' ? 'Close' : 'Cancel'}
                    </button>
                    {activeTab === 'settings' ? (
                      <button
                        onClick={handleSaveProvider}
                        disabled={saving}
                        className="btn-primary px-6 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2"
                      >
                        {saving ? 'Saving...' : 'Save & Connect'}
                      </button>
                    ) : (
                      <button
                        onClick={() => setActiveTab('settings')}
                        className="btn-primary px-6 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2"
                      >
                        Configure Sync
                      </button>
                    )}
                  </div>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  )
}

export default Integrations
